site_name: Waze
theme:
  name: 'material'

extra_css:
  - css/extra_css.css

nav:
  - Home: README.md
  - Planejamento: planejamento.md
  - Pré-rastreabilidade: 
    - RichPicture: richPicture.md
    
